[package]
name = "nrepl-client-demo"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_bencode = "0.2"
uuid = { version = "1.0", features = ["v4"] }
